adminUser: ENC[AES256_GCM,data:Fs5cgD4=,iv:m7qsRrtjJljDthSGg2KJLCT0eTfZ/Ys/tgeMDPoWNtM=,tag:sWTmkOcvXtVbuo0qabCVGg==,type:str]
adminPassword: ENC[AES256_GCM,data:9qpX3N3H/di4Bi8L8p7KVQ==,iv:FBR5C23Jg2yd4QxdO75el27cWdAZjUiaCV4DmcJGfjc=,tag:WQCtvt/cXa9MVISdlyURlw==,type:str]
sops:
    age:
        - recipient: age1kla7282x4aklv86808ft3y5y8kgme5csrnqmht6wemkgfnmg2pqqh5gggx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQkIxUGhmSU9haTA3YTJm
            MEgweWlWNjR5OGtMR3BmOXNuSHFycnVPL2pFCjIwVHpoOVNMa1V0NUJoL1puVjJ3
            cWJoeWhHenlQYktUbkorQXo2dThaemcKLS0tIHB2WXpOSHBkL2hIanQ2TEVxMWRi
            T01Id3MydC9UdnRYcjdoZXk0VzlMVm8KlQ4X25AhJ8wH5FuSOg3bWwdWmwv2wFzq
            +kgYHI4+ulZyUhajifa0qtikawR+YrruQC8avVmP3GHycMoDVzsO+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T06:09:42Z"
    mac: ENC[AES256_GCM,data:FnQvrS63jVuvhARTNhG+brtuI9eUn6gdO3VzW89PZ0VbZwlMoQ9CZgrXAmRawxq4VRZYtKsr6hXvX7DDrldGifeqnkrWv11h/0QqAhkpSVtf/0SW7IPYMimclfI4SpnZ0BnTsG9FAKd+ygbzo4TAzW5sUlJDNhYmC0QbyDh5oqs=,iv:Glwm6OrCfrHTCgy5NmtTJ2HdWnLeqgohPnbIq6AT8IQ=,tag:7wG8y8sRzxlBO5hhw3nfCA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
