apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

helmCharts:
  - name: grafana
    version: 10.2.0
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    valuesFile: custom-values.encrypted.yaml

