username: ENC[AES256_GCM,data:G3SZyMc=,iv:D129tdj+L/qZTb2xPpqDsMYDpcg7LA542uChApkfx6E=,tag:wjQp/QrpJLi3KyAdQDlVuA==,type:str]
password: ENC[AES256_GCM,data:IdiQrz+UK/I=,iv:fou1qeKxCtHp2lO9fLPsFYDNNTs+Jxs36djxXhO6Bx8=,tag:JbZlvz1FEp09MOuNbFXQ3g==,type:str]
sops:
    age:
        - recipient: age1kla7282x4aklv86808ft3y5y8kgme5csrnqmht6wemkgfnmg2pqqh5gggx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL2M3Y2tZR2x6TTdCaVkz
            Q1RaKzFjU2VZOHQ2OVBSZlVaM3RYYW41cjJnCng2NEhNL2lVSUZsdWVCL29pVGU4
            amZYTWpJMTlzTkx1eUh4cENiNkhqZlkKLS0tIEhZOXF5R0FFZ01obXBhSjZUYzJ0
            cGtqOGcwbVYvbGVtSHdXMUdsOThWK2cK+9fV8LmEtCxTbvSBOcZmemVSABz8dpRs
            QfTP2BNWVziXEpCXKeEIVP31gQrdhYYjNdnFl5ZeX4Yqg8HGwX+PJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:40:10Z"
    mac: ENC[AES256_GCM,data:ZtJYAuKgQ+oMePW5cQXfrDeHI6jvN7bKAb2h9mQeNO8daHjgpKWVt0B09a8+4ZWVJtUtRPxcQad5XNlAWa4PbtjAhkUNFo3WWNg/4ttav5gZ/ohN+Gf8tBXSRVxyjangmUpowbJNI9mZ+sbIJ4pb218ctYmvDWAd8wX0yRcVIE8=,iv:fI7PjFQqLRJqEXgKP6YCRJZhbTmsjbUcKviyZVBuQjc=,tag:t0GFgUoRNRW6tZKxHCSvnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
