apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend-helm

helmGlobals:
  chartHome: ./

helmCharts:
  - releaseName: backend-helm
    namespace: backend-helm
    name: charts
    version: 0.1.0
    valuesFile: ./encrypted-values.yaml


generators:
  - ./secret-generator.yaml