apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend-helm

helmGlobals:
  chartHome: charts
helmCharts:
  - releaseName: backend-helm
    namespace: backend-helm
    name: backend-helm
    version: 0.1.0
    valuesFile: ./custom-values.yaml


generators:
  - ./secret-generator.yaml