apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-stack

helmCharts:
  - name: prometheus-stack
    version: 79.8.2
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus-stack
    valuesFile: values.yaml
